monolog:
    channels:
        - payone
        - payone_transaction_forward

    handlers:
        payoneLogger:
            type: rotating_file
            path: "%kernel.logs_dir%/payone.log"
            level: info
            channels: [ "payone" ]
        payoneTransactionForwardLogger:
            type: rotating_file
            path: "%kernel.logs_dir%/payone_transaction_forward.log"
            level: info
            channels: [ "payone_transaction_forward" ]
