import '../commands/buy_demo_article'
import '../commands/checkout_buy'
import '../commands/finish_checkout'
import '../commands/login'
import '../commands/register'
import '../commands/select_payment_method'
