name: Create Archive
on: [tag]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set Tag env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
    - name: build zip
      uses: thedoctor0/zip-release@master
      with:
        filename: 'PayonePayment-$RELEASE_VERSION.zip'
        exclusions: '*.git* bin tests .* composer.lock php*'
    - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: 'PayonePayment-$RELEASE_VERSION.zip'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}